### ISSUE TITLE
Missing g++ on compute

### ISSUE THREAD

**Issue by sleepyorion** [oneops/circuit-oneops-1#197]
On a pristine compute where g++ (gcc-c++) is not installed by default will cause "os" recipe to fail while trying to  install unf_ext -v 0.0.7.2 gem.  Since "os" is so early in the install part we must provide g++ dependency or provide pre-compiled gem package.

**Comment by Gopinath17** [comment]
Is this issue still existing ?.. Because we are not facing any issue while creating compute. If yes please provide the steps to reproduce.
