### ISSUE TITLE
Refactor and Write Unit Test Cases for Azure DNS Build Entries List Recipe.

### ISSUE THREAD

**Issue by sheraz-bashir-confiz** [oneops/circuit-oneops-1#43]
@shaffan-chaudhry-confiz
1.   Fix Robocop and foodcritic issues.
2.   Create LWRP and Unit Test cases using ChefSpec.
3.   Verify unit tests.
4.   Integration test
5.   Generate pull request.

**Comment by kpgriffith** [comment]
build_entry_list was removed because it was duplicate code.  Closing the issue.
