### ISSUE TITLE
Write Unit Tests for Azure "build_network_profile_for_add_node" recipe

### ISSUE THREAD

**Issue by sheraz-bashir-confiz** [oneops/circuit-oneops-1#69]
1.  Create Class Library
2.  fix Robocop and foodcritic issues
3.  Write unit test cases with 100% coverage
4.  Get your code peer reviewed
5.   Integration test
6.   Generate pull request

Integration testing involves following items
1. Make a deployment that uses this recipe
2. Verify that your recipe is executed and produced the correct result
3. Verity that the deployment created is running without issues
4. Remove the deployment/resource groyp after testing is complete

**Comment by kpgriffith** [comment]
Completed and closed
