### ISSUE TITLE
Write Unit Test for "Delete Resource group" Recipe.

### ISSUE THREAD

**Issue by sheraz-bashir-confiz** [oneops/circuit-oneops-1#74]
1.	Fix Robocop and foodcritic issues
2.	Write unit test cases with 100% coverage
3.	Get your code peer reviewed
4.	Integration test
5.	Generate pull request
Integration testing involves following items
1. Make a deployment that uses this recipe
2. Verify that your recipe is executed and produced the correct result
3. Verity that the deployment created is running without issues
4. Remove the deployment/resource groyp after testing is complete

**Comment by kpgriffith** [comment]
Completed and merged
