### ISSUE TITLE
Write Unit Test Case for Azure->Add Node Recipe

### ISSUE THREAD

**Issue by sheraz-bashir-confiz** [oneops/circuit-oneops-1#75]
1.  Fix Robocop and foodcritic issues
2.  Write unit test cases with 100% coverage
3.  Get your code peer reviewed
4.  Integration test
5.  Generate pull request
   Integration testing involves following items
6. Make a deployment that uses this recipe
7. Verify that your recipe is executed and produced the correct result
8. Verity that the deployment created is running without issues
9. Remove the deployment/resource groyp after testing is complete

**Comment by kpgriffith** [comment]
Closing this issue due to change of strategy.  The Azure cookbooks will be updated to use the fog-azure-rm library.
