### ISSUE TITLE
Azure Application Gateway

### ISSUE THREAD

**Issue by kpgriffith** [oneops/circuit-oneops-1#77]
We are unable to add certs to the AzureLB and Application Gateway is how this is done.

This functionality needs to be added into OneOps

**Comment by schwankl** [comment]
@kpgriffith you saying a pack is missing the lb-certificate and relation to lb ?  If the pack extends genericlb then it should have it...just have whatever pack extend genericlb

**Comment by kpgriffith** [comment]
@schwankl No.  I'm saying the azure_lb recipe will have the lb-certificate, but Azure LB in Azure doesn't allow us to set the certificate.  Azure created the Application Gateway that will allow this.

**Comment by kfilipovski** [comment]
@kpgriffith can it be implemented without changing the pack structure? I.e can the Application Gateway be called from the lb component? Is it just matter of doing the work or we are stuck because of the way Azure offers this?

**Comment by kpgriffith** [comment]
@kfilipovski More research is needed, but at first thought I don't think we need to change the pack structure for this.  I really think we just need to make additional calls to this api.  I will do more research and let you know more details.

**Comment by kpgriffith** [comment]
Completed and merged
